build: upgrade ng to v22 #TINFR-3745 (#3824)
* build: pnpm ng update @angular/cli@22 @angular-eslint/schematics@22 @angular/cdk@22 @angular/core@22 @angular/common@22 @angular/compiler@22 @angular/forms@22 @angular/platform-browser@22 @angular/router@22 @angular-devkit/core@22 @angular-devkit/schematics@22 @angular-eslint/builder@22 @angular-eslint/eslint-plugin@22 @angular-eslint/eslint-plugin-template@22  @angular-eslint/template-parser@22 @angular/build@22  @angular/compiler-cli@22 @angular/language-service@22 @schematics/angular@22 ng-packagr@22 angular-eslint@22

* build: update ng to v22 in peerDependencies manually

* build: update schematics manually

* build: update guide docs manually

* build: pnpm run lint and solve 946 errors: Components should not opt out of the default `ChangeDetectionStrategy.OnPush` change detection strategy

* build: pnpm run build and temporarily solve error: NG4003: Angular compiler option "extendedDiagnostics" is configured, however "strictTemplates" is disabled.

* build: pnpm run build and solve error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0

* build: pnpm run build and solve error TS2416: Property 'thyActive' in type 'ThyCollapseItem' is not assignable to the same property in base type 'IThyCollapseItemComponent'

* build: pnpm run build and solve error and solve error TS2591: Cannot find name 'xxx'

* build: pnpm run build-site and temporarily solve  [ERROR] No matching export in "node_modules/.pnpm/@angular+core@22.0.2_@angular+compiler@22.0.2_rxjs@7.8.2_zone.js@0.15.1/node_modules/@angular/core/fesm2022/core.mjs" for import "ComponentFactoryResolver"

* build: pnpm run test-schematics and solve error ReferenceError: exports is not defined in ES module scope

* build: pnpm run test and solve error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0

* build: pnpm run test and solve errors

* build: remove changeDetection: ChangeDetectionStrategy.OnPush manually because 22 uses OnPush by default